(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const escapeHTML = (value = '') => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
  const image = (src, alt, className = '') => src ? `<img class="${className}" src="${escapeHTML(src)}" alt="${escapeHTML(alt)}" loading="lazy">` : `<div class="image-placeholder ${className}" role="img" aria-label="Imagem ainda não adicionada">F</div>`;
  const query = new URLSearchParams(location.search).get('grupo');
  function render(group, projects) {
    const projectList = group.projects?.length ? group.projects : (group.project?.title ? [group.project] : []);
    const project = projectList[0] || {};
    $('#group-content').innerHTML = `<section class="group-hero" style="--accent:${escapeHTML(group.accent || '#e8b63f')}"><div class="group-logo">${image(group.logo, `Logo do grupo ${group.name}`, 'logo-image')}</div><div><p class="section-kicker">grupo Fecart</p><h1>${escapeHTML(group.name)}</h1><p class="group-description">${escapeHTML(group.description || 'Este grupo ainda está preparando sua apresentação.')}</p></div></section><section class="group-project section-block"><div class="block-heading"><p class="section-kicker">o projeto</p><h2>${escapeHTML(project.title || 'Projeto em construção')}</h2></div><div class="project-detail"><div><p>${escapeHTML(project.description || 'A descrição detalhada do projeto será adicionada aqui.')}</p><p>${escapeHTML(project.details || '')}</p></div><div class="project-related">${projects.length ? projects.map(item => `<a href="index.html#projetos" class="related-project"><span>${escapeHTML(item.year || '')}</span><strong>${escapeHTML(item.title)}</strong><small>ver projeto completo ↗</small></a>`).join('') : '<p class="empty-detail">Os projetos deste grupo aparecerão aqui.</p>'}</div></div></section><section class="members-section section-block"><div class="block-heading"><p class="section-kicker">quem constrói</p><h2>Pessoas por<br><em>trás da ideia.</em></h2></div><div class="members-grid">${group.members?.length ? group.members.map(member => `<article class="member-card">${image(member.photo, `Foto de ${member.name}`, 'member-photo')}<h3>${escapeHTML(member.name)}</h3><p>${escapeHTML(member.role || 'Integrante')}</p></article>`).join('') : '<p class="empty-detail">As fotos, nomes e funções dos integrantes serão adicionados aqui.</p>'}</div></section><section class="gallery-section section-block"><div class="block-heading"><p class="section-kicker">por trás de tudo</p><h2>O processo<br><em>em imagens.</em></h2><p>Uma galeria para registrar testes, protótipos, erros, descobertas e todas as etapas que fazem o projeto acontecer.</p></div><div class="process-gallery">${group.gallery?.length ? group.gallery.map(item => `<figure>${image(item.src, item.alt || 'Registro do processo', 'gallery-image')}<figcaption>${escapeHTML(item.caption || '')}</figcaption></figure>`).join('') : '<div class="gallery-empty">A galeria do processo será preenchida quando as imagens forem adicionadas.</div>'}</div></section>`;
    document.title = `${group.name} · Fecart`;
  }
  async function init() { try { const response = await fetch('data/content.json'); const initial = await response.json(); let data = initial; try { const draft = JSON.parse(localStorage.getItem('fecart-content-draft') || 'null'); if (draft && draft.contentVersion === initial.contentVersion) data = draft; } catch {} const group = data.groups.find(item => item.id === query) || data.groups[0]; const projects = data.projects.filter(item => item.groupId === group.id); render(group, projects); } catch { $('#group-content').innerHTML = '<p class="empty-detail">Não foi possível carregar este grupo agora.</p>'; } }
  init();
})();
