(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const escapeHTML = (value = '') => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
  const image = (src, alt, className = '') => src ? `<img class="${className}" src="${escapeHTML(src)}" alt="${escapeHTML(alt)}" loading="lazy">` : `<div class="image-placeholder ${className}" role="img" aria-label="Imagem ainda não adicionada">F</div>`;
  const placeholderMedia = (label, type = 'photo') => `<div class="media-placeholder ${type}-placeholder" role="img" aria-label="${escapeHTML(label)}"><span>${type === 'video' ? '▶' : 'F'}</span><small>${escapeHTML(label)}</small></div>`;
  const query = new URLSearchParams(location.search).get('grupo');
  let data;
  let activeGroup;
  const editorField = (label, key, value, multiline = false) => `<div class="editor-field"><label>${label}</label>${multiline ? `<textarea data-group-field="${key}">${escapeHTML(value || '')}</textarea>` : `<input data-group-field="${key}" value="${escapeHTML(value || '')}">`}</div>`;

  function render(group, projects) {
    activeGroup = group;
    const project = group.projects?.length ? group.projects[0] : (group.project?.title ? group.project : {});
    const memberCount = group.id === 'sabor-robotica' ? 4 : 5;
    const members = Array.from({ length: memberCount }, (_, index) => group.members?.[index] || { name: `Integrante ${index + 1}`, role: 'Função a definir', photo: '' });
    const gallery = group.gallery?.length ? group.gallery : [{ type: 'photo', caption: 'Foto do processo' }, { type: 'photo', caption: 'Protótipo em teste' }, { type: 'video', caption: 'Vídeo do making of' }];
    $('#group-content').innerHTML = `<section class="group-hero" style="--accent:${escapeHTML(group.accent || '#e8b63f')}"><div class="group-logo">${image(group.logo, `Logo do grupo ${group.name}`, 'logo-image')}</div><div><p class="section-kicker">grupo Fecart</p><h1>${escapeHTML(group.name)}</h1><p class="group-description">${escapeHTML(group.description || 'Este grupo ainda está preparando sua apresentação.')}</p></div></section><section class="members-section section-block"><div class="block-heading"><p class="section-kicker">quem constrói</p><h2>Pessoas por<br><em>trás da ideia.</em></h2></div><div class="members-grid">${members.map((member, index) => `<article class="member-card">${member.photo ? image(member.photo, `Foto de ${member.name || `Integrante ${index + 1}`}`, 'member-photo') : placeholderMedia(`Integrante ${index + 1}`, 'member')}<h3>${escapeHTML(member.name || `Integrante ${index + 1}`)}</h3><p>${escapeHTML(member.role || 'Função a definir')}</p></article>`).join('')}</div></section><section class="group-project section-block"><div class="block-heading"><p class="section-kicker">o projeto</p><h2>${escapeHTML(project.title || 'Projeto em construção')}</h2></div><div class="project-detail"><div><div class="project-main-media">${project.image ? image(project.image, `Foto do projeto ${project.title}`, 'project-main-image') : placeholderMedia('Foto principal do projeto')}</div><p>${escapeHTML(project.description || 'A descrição detalhada do projeto será adicionada aqui.')}</p><p>${escapeHTML(project.details || '')}</p></div><div class="project-related">${projects.length ? projects.map(item => `<a href="index.html#projetos" class="related-project"><span>${escapeHTML(item.year || '')}</span><strong>${escapeHTML(item.title)}</strong><small>ver projeto completo ↗</small></a>`).join('') : '<p class="empty-detail">Os projetos deste grupo aparecerão aqui.</p>'}</div></div></section><section class="gallery-section section-block"><div class="block-heading"><p class="section-kicker">por trás de tudo</p><h2>O processo<br><em>em imagens.</em></h2><p>Fotos e vídeos para registrar testes, protótipos, erros, descobertas e todas as etapas que fazem o projeto acontecer.</p></div><div class="process-gallery">${gallery.map(item => `<figure>${item.type === 'video' ? placeholderMedia(item.caption || 'Vídeo do making of', 'video') : item.src ? image(item.src, item.alt || 'Registro do processo', 'gallery-image') : placeholderMedia(item.caption || 'Foto do processo')}<figcaption>${escapeHTML(item.caption || '')}</figcaption></figure>`).join('')}</div></section>`;
    document.title = `${group.name} · Fecart`;
  }

  function renderEditor() {
    const group = activeGroup;
    const project = group.project || {};
    const fields = `${editorField('Logo (URL ou caminho)', 'logo', group.logo)}${editorField('Descrição do grupo', 'description', group.description, true)}${editorField('Integrantes em JSON', 'members', JSON.stringify(group.members || [], null, 2), true)}${editorField('Projeto em JSON', 'project', JSON.stringify(project, null, 2), true)}${editorField('Galeria de fotos e vídeos em JSON', 'gallery', JSON.stringify(group.gallery || [], null, 2), true)}`;
    $('#group-editor-fields').innerHTML = fields;
    $$('[data-group-field]').forEach(field => field.addEventListener('input', () => updateGroupField(field.dataset.groupField, field.value)));
  }
  const $$ = selector => [...document.querySelectorAll(selector)];
  function updateGroupField(key, value) { if (['members', 'project', 'gallery'].includes(key)) { try { activeGroup[key] = JSON.parse(value); } catch { return; } } else activeGroup[key] = value; data.contentVersion = 4; localStorage.setItem('fecart-content-draft', JSON.stringify(data)); const projects = data.projects.filter(item => item.groupId === activeGroup.id); render(activeGroup, projects); renderEditor(); $('#group-editor-status').textContent = 'Alteração salva neste navegador.'; }
  function resetGroup() { localStorage.removeItem('fecart-content-draft'); const group = data.groups.find(item => item.id === query) || data.groups[0]; render(group, data.projects.filter(item => item.groupId === group.id)); renderEditor(); $('#group-editor-status').textContent = 'Conteúdo original restaurado.'; }
  function initEditor() { $('#group-editor-close').addEventListener('click', () => { $('#group-editor-panel').hidden = true; }); $('#group-editor-save').addEventListener('click', () => { data.contentVersion = 4; localStorage.setItem('fecart-content-draft', JSON.stringify(data)); $('#group-editor-status').textContent = 'Alterações salvas neste navegador.'; }); $('#group-editor-reset').addEventListener('click', resetGroup); document.addEventListener('keydown', event => { const maintenanceKey = event.key === '\\' || event.key === '|' || event.code === 'Backslash' || event.code === 'IntlBackslash'; if (event.ctrlKey && event.shiftKey && maintenanceKey) { event.preventDefault(); const panel = $('#group-editor-panel'); panel.hidden = !panel.hidden; if (!panel.hidden) { renderEditor(); $('#group-editor-fields input')?.focus(); } } if (event.key === 'Escape') $('#group-editor-panel').hidden = true; }); }
  async function init() { try { const response = await fetch('data/content.json'); const initial = await response.json(); data = initial; try { const draft = JSON.parse(localStorage.getItem('fecart-content-draft') || 'null'); if (draft && draft.contentVersion === initial.contentVersion) data = draft; } catch {} const group = data.groups.find(item => item.id === query) || data.groups[0]; render(group, data.projects.filter(item => item.groupId === group.id)); initEditor(); } catch { $('#group-content').innerHTML = '<p class="empty-detail">Não foi possível carregar este grupo agora.</p>'; } }
  init();
})();
