(() => {
  'use strict';
  const supabase = window.FECART_SUPABASE || {};
  const fallbackQuestions = [
    { id: 'q1', category: 'Fecart', prompt: 'O que a Fecart incentiva nos seus projetos?', options: ['Curiosidade, colaboração e robótica', 'Competição sem colaboração', 'Apenas teoria'], correct_index: 0 },
    { id: 'q2', category: 'Lira Laser (Instrumentação)', prompt: 'Em vez de usar cordas normais, o que a Lira Laser usa para fazer som?', options: ['Fios de nylon extremamente finos.', 'Feixes de luz laser.', 'Botões de plástico sensíveis ao toque.', 'Sensores de movimento infravermelho.'], correct_index: 1 },
    { id: 'q3', category: 'Lira Laser (Instrumentação)', prompt: 'Como a Lira Laser ajuda na área da saúde?', options: ['Ensinando teoria musical básica para iniciantes.', 'Auxiliando na reabilitação motora e terapia sensorial.', 'Medindo os batimentos cardíacos do paciente pelo toque.', 'Melhorando a audição através de frequências agudas.'], correct_index: 1 },
    { id: 'q4', category: 'Lira Laser (Instrumentação)', prompt: 'Para qual público a Lira Laser foi pensada principalmente?', options: ['Pessoas com restrições de mobilidade ou sensibilidade física.', 'Crianças que estão tendo o primeiro contato com a música.', 'Músicos profissionais que buscam ritmos eletrônicos.', 'Escolas de música clássica e orquestras.'], correct_index: 0 },
    { id: 'q5', category: 'Bengala Inteligente (Acessibilidade)', prompt: 'Como a Bengala Inteligente consegue “sentir” obstáculos altos como galhos ou lixeiras suspensas?', options: ['Através de uma pequena câmera instalada na ponta.', 'Emitindo ondas sonoras e estudando o eco, como um sonar.', 'Conectando-se ao GPS do celular para Bluetooth.', 'Usando um laser que escaneia o formato da calçada.'], correct_index: 1 },
    { id: 'q6', category: 'Bengala Inteligente (Acessibilidade)', prompt: 'O que acontece se a pessoa que usa a bengala se sentir em perigo, cair ou se desorientar?', options: ['Ela aperta um botão de emergência que liga para um familiar ou cuidador.', 'A Bengala aciona uma luz forte para chamar a atenção ao redor.', 'O dispositivo envia uma mensagem de texto para o hospital mais próximo.', 'A bengala vibra sem parar até que o perigo passe.'], correct_index: 0 },
    { id: 'q7', category: 'Bengala Inteligente (Acessibilidade)', prompt: 'Qual é uma das grandes vantagens sociais da Bengala Inteligente?', options: ['Criar um aplicativo gratuito de mapas com áudio para pessoas cegas.', 'Oferecer uma tecnologia assistiva de baixo custo e alta eficiência.', 'Substituir completamente a necessidade de pisos táteis nas calçadas.', 'Permitir que o usuário grave os caminhos que faz todos os dias.'], correct_index: 1 },
    { id: 'q8', category: 'GuideBot (Carrinho Autônomo)', prompt: 'Qual é o principal objetivo do carrinho GuideBot?', options: ['Monitorar a segurança das ruas do bairro de forma automática.', 'Ajudar pessoas com deficiência visual a se locomoverem com mais segurança.', 'Carregar pequenos objetos pessoais ou ajudar durante uma caminhada.', 'Substituir as cadeiras de rodas elétricas no futuro.'], correct_index: 1 }
  ];
  let questions = [];
  const $ = selector => document.querySelector(selector);
  const escapeHTML = (value = '') => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
  const apiUrl = path => `${supabase.url || ''}/rest/v1/${path}`;
  const headers = () => ({ apikey: supabase.anonKey || '', Authorization: `Bearer ${supabase.anonKey || ''}`, 'Content-Type': 'application/json' });

  async function loadQuestions() { if (supabase.url && supabase.anonKey) { try { const response = await fetch(apiUrl('fecart_quiz_questions?select=*&active=eq.true&order=sort_order.asc')); if (response.ok) { const remote = await response.json(); if (remote.length) return remote; } } catch (error) { console.warn('Quiz remoto indisponível.', error); } } return fallbackQuestions; }
  function renderQuestions() { $('#questions').innerHTML = questions.map((question, index) => `<fieldset class="question"><legend><span>${String(index + 1).padStart(2, '0')}</span><small>${escapeHTML(question.category || 'Quiz da Fecart')}</small>${escapeHTML(question.prompt)}</legend>${question.options.map((option, optionIndex) => `<label class="answer"><input type="radio" name="question-${escapeHTML(question.id)}" value="${optionIndex}" required><span>${escapeHTML(option)}</span></label>`).join('')}</fieldset>`).join(''); $('#quiz-progress').textContent = `${questions.length} perguntas · uma resposta por questão`; }
  function scoreQuiz() { return questions.reduce((score, question) => { const answer = document.querySelector(`input[name="question-${question.id}"]:checked`); return score + (answer && Number(answer.value) === Number(question.correct_index) ? 1 : 0); }, 0); }
  async function saveAttempt(name, score, answers) { if (!supabase.url || !supabase.anonKey) return false; const response = await fetch(apiUrl('fecart_quiz_attempts'), { method: 'POST', headers: { ...headers(), Prefer: 'return=minimal' }, body: JSON.stringify({ participant_name: name, score, total_questions: questions.length, answers }) }); return response.ok; }
  async function loadRanking() { const ranking = $('#ranking'); try { if (!supabase.url || !supabase.anonKey) throw new Error('Sem banco'); const response = await fetch(apiUrl('fecart_quiz_attempts?select=participant_name,score,total_questions,created_at&order=score.desc,created_at.asc&limit=20'), { headers: headers() }); if (!response.ok) throw new Error('Falha no ranking'); const rows = await response.json(); renderRanking(rows); } catch { let rows = []; try { rows = JSON.parse(localStorage.getItem('fecart-quiz-ranking') || '[]'); } catch {} renderRanking(rows.sort((a, b) => b.score - a.score).slice(0, 20)); } }
  function renderRanking(rows) { $('#ranking').innerHTML = rows.length ? rows.map((row, index) => `<div class="ranking-row"><strong>${String(index + 1).padStart(2, '0')}</strong><span>${escapeHTML(row.participant_name)}</span><b>${row.score}/${row.total_questions}</b></div>`).join('') : '<p>Nenhum resultado ainda. Seja o primeiro a participar.</p>'; }
  async function submitQuiz(event) { event.preventDefault(); const name = $('#participant-name').value.trim(); const score = scoreQuiz(); const answers = questions.map(question => ({ question_id: question.id, answer: Number(document.querySelector(`input[name="question-${question.id}"]:checked`).value), correct: Number(question.correct_index) })); $('#form-error').textContent = ''; const saved = await saveAttempt(name, score, answers); if (!saved) { const local = JSON.parse(localStorage.getItem('fecart-quiz-ranking') || '[]'); local.push({ participant_name: name, score, total_questions: questions.length, created_at: new Date().toISOString() }); localStorage.setItem('fecart-quiz-ranking', JSON.stringify(local)); } $('#quiz-form').hidden = true; $('#quiz-result').hidden = false; $('#score').textContent = `${score} / ${questions.length}`; $('#result-message').textContent = score === questions.length ? 'Você acertou tudo. Que curiosidade bonita.' : `Você acertou ${score} de ${questions.length}. Continue explorando os projetos da Fecart.`; await loadRanking(); }
  async function init() { questions = await loadQuestions(); $('#start-quiz').addEventListener('click', () => { const name = $('#participant-name').value.trim(); if (!name) { $('#start-error').textContent = 'Digite seu nome para começar.'; return; } $('#start-error').textContent = ''; $('#quiz-start').hidden = true; $('#quiz-form').hidden = false; renderQuestions(); }); $('#quiz-form').addEventListener('submit', submitQuiz); $('#see-ranking').addEventListener('click', () => $('#ranking-section').scrollIntoView({ behavior: 'smooth' })); await loadRanking(); }
  init();
})();
